title: شیدا
description: تفالی بر شعر حافظ

author: bonyad
timezone: +03:30

url: https://hafez-fal.ir/
root: /

static: /static/

icon: /static/theme/tahrir/img/icon.png

post_num: all
archive_post_num: all
feed_output: atom.xml

default_floor: ghazal
default_markup: mmd

template: tahrir

github: https://github.com/bonyad
