title: فال حافظ
description: تفالی بر اشعار حافظ
author: bonyad
language: Farsi

url: https://hafez-fal.ir/
root: /

default_extension: md

permalink: ghazal/:title/

post_num: all
archive_post_num: all
post_sort: reverse

lists:
  - list
  - indexes


